name: Deploy dan-plugin-kartverket

on:
 push:
   branches: [ main ]
   paths-ignore:
     - '**/README.md'
     - '**/*.yml'
 workflow_dispatch:

jobs:
 run:
  # Pinning to commit d08132e for stability; this commit includes bugfixes for deployment issues as of 2024-06-01
   uses: data-altinn-no/deploy-actions/.github/workflows/dan-deploy-flow.yml@e9a1d62778d9d2f4e8c2245027fb2750fd230e0a
   permissions:
    actions: read
    contents: read
    security-events: write
   with:
     artifact_name: 'dan-plugin-kartverket' # Can be omitted, defaults to 'artifact'
     function_project_path: 'src/Dan.Plugin.Kartverket'
   secrets:
     function_app_name: ${{ secrets.FUNCTIONAPP_NAME }}
     publish_profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}
     azure_artifact_pat: ${{ secrets.AZURE_ARTIFACTS_PAT }}
     azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
     resource_group_prod: ${{ secrets.RESOURCE_GROUP_PROD }}
